import * as express from 'express';
import * as cors from 'cors';
import authRoutes from './routes/auth';
import productRoutes from './routes/product';
const app = express();
app.use(cors());
app.use(express.json());
app.use('/auth', authRoutes);
app.use('/products', productRoutes);
const PORT = 3000;
app.listen(PORT, () => console.log(`Server running on http://localhost:${PORT}`));